name: dsci-532-group-31
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.0
  - numpy=1.24
  - scikit-learn=1.3
  - matplotlib=3.7
  - jupyter=1.0
  - dash>=2.16
  - pip
  - pip:
      - plotly>=5.18
